export const GET_STREAMS_BEGIN = 'GET_STREAMS_BEGIN';
export const GET_STREAMS_SUCCESS = 'GET_STREAMS_SUCCESS';
export const GET_STREAMS_ERROR = 'GET_STREAMS_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const GET_TVSHOW_BEGIN = 'GET_TVSHOW_BEGIN';
export const GET_TVSHOW_SUCCESS = 'GET_TVSHOW_SUCCESS';
export const GET_TVSHOW_ERROR = 'GET_TVSHOW_ERROR';


export const TOGGLE_TO_MOVIE = 'TOGGLE_TO_MOVIE';
export const TOGGLE_TO_TVSHOW = 'TOGGLE_TO_TVSHOW';